# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-12 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('game_price', models.FloatField(default=0)),
                ('genre', models.CharField(max_length=15)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
