# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-12 10:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20170612_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='photo',
            field=models.ImageField(default=datetime.datetime(2017, 6, 12, 10, 47, 4, 710436, tzinfo=utc), upload_to=b''),
            preserve_default=False,
        ),
    ]
