# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-12 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-created_date']},
        ),
        migrations.AddField(
            model_name='game',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='photo',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
    ]
