# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epinmain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=225, unique=True),
        ),
    ]
